/*
 * This source file was generated by the Gradle 'init' task
 */
package io.jespen;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RunnerTest {
    @Test void appHasAGreeting() {
    }
}
